install group and passwd

diff --git a/bin/guru b/bin/guru
--- a/bin/guru
+++ b/bin/guru
@@ -87,8 +87,10 @@ pkg-install () {
     echo "$(style +b green)installing $pkg_spec$(style)"
     pkg-install-apt "$pkg_root" "$pkg_spec"
     pkg-install-lib "$pkg_root" "$pkg_spec"
-    pkg-install-fs "$pkg_root" "$pkg_spec"
     pkg-install-bin "$pkg_root" "$pkg_spec"
+    pkg-install-fs "$pkg_root" "$pkg_spec"
+    pkg-install-group "$pkg_root" "$pkg_spec"
+    pkg-install-passwd "$pkg_root" "$pkg_spec"
     echo "$(style green)completed installing $pkg_spec$(style)"
 }
 
@@ -129,6 +131,45 @@ pkg-install-fs () {
     cp -vrT "$pkg_root/fs" /
 }
 
+pkg-install-group () {
+    local pkg_root="$1"
+    local pkg_spec=${2:-$(basename $(realpath "$pkg_root"))}
+    local entry
+    local -a fields
+    local name pw gid users
+
+    if ! test -f "$pkg_root/group"; then
+        return
+    fi
+
+    echo "$(style +bu white)setting up local groups$(style)"
+
+    while read entry; do
+        IFS=: read -ra fields <<< "$entry"
+        name=${fields[0]}
+        pw=${fields[1]}
+        gid=${fields[2]}
+        users=${fields[3]}
+
+        echo -n "$entry "
+
+        if test ${#fields[@]} -lt 3 -o ${#fields[@]} -gt 4; then
+            echo "$(style red)skipping (invalid)$(style)"
+            #echo "$(style red)skipping invalid '$name' group entry$(style)"
+        elif getent group "$name" &>/dev/null; then
+            echo "$(style red)skipping (exists)$(style)"
+            #echo "$(style red)skipping existing '$name' group entry$(style)"
+        elif test "$pw" != x; then
+            echo "$(style red)ignoring password$(style)"
+            #echo "$(style red)ignoring password for '$name'$(style)"
+        else
+            #echo "adding entry '$name' to group DB"
+            echo
+            groupadd -g "$gid" -U "$users" "$name"
+        fi
+    done < "$pkg_root/group"
+}
+
 pkg-install-lib () {
     local pkg_root="$1"
     local pkg_spec=${2:-$(basename $(realpath "$pkg_root"))}
@@ -139,6 +180,49 @@ pkg-install-lib () {
 
     echo "$(style +bu white)installing libraries$(style)"
     cp -vrT "$pkg_root/lib" "$prefix/lib"
+}
+
+pkg-install-passwd () {
+    local pkg_root="$1"
+    local pkg_spec=${2:-$(basename $(realpath "$pkg_root"))}
+    local entry
+    local -a fields
+    local name pw uid gid gecos home shell
+
+    if ! test -f "$pkg_root/passwd"; then
+        return
+    fi
+
+    echo "$(style +bu white)setting up local users$(style)"
+
+    while read entry; do
+        IFS=: read -ra fields <<< "$entry"
+        name=${fields[0]}
+        pw=${fields[1]}
+        uid=${fields[2]}
+        gid=${fields[3]}
+        info=${fields[4]}
+        home=${fields[5]}
+        sh=${fields[6]}
+
+        echo -n "$entry "
+
+        if test ${#fields[@]} -ne 7; then
+            echo "$(style red)skipping (invalid)$(style)"
+            #echo "$(style red)skipping invalid '$name' passwd entry$(style)"
+        elif getent passwd "$name" &>/dev/null; then
+            echo "$(style red)skipping (exists)$(style)"
+            #echo "$(style red)skipping existing '$name' passwd entry$(style)"
+        elif test "$pw" != x; then
+            echo "$(style red)ignoring password$(style)"
+            #echo "$(style red)ignoring password for '$name'$(style)"
+        else
+            #echo "adding entry '$name' to passwd DB"
+            #echo "$entry"
+            echo
+            useradd -u "$uid" -g "$gid" -c "$info" -md "$home" -s "$sh" "$name"
+        fi
+    done < "$pkg_root/passwd"
 }
 
 pkg-verify () {
