support for --prefix option

diff --git a/bin/guru b/bin/guru
--- a/bin/guru
+++ b/bin/guru
@@ -1,7 +1,8 @@
 #!/bin/bash -e
 
 declare exe=guru
-declare cmdname=
+declare cmd=
+declare prefix=/usr/local
 
 detect-color () {
     local colors=$(tput colors 2>/dev/null)
@@ -90,7 +91,7 @@ pkg-install-bin () {
     fi
 
     echo "$(style bold white underline)installing binaries$(style)"
-    cp -vrT "$pkg_root/bin" /usr/local/bin
+    cp -vrT "$pkg_root/bin" "$prefix/bin"
 }
 
 pkg-verify () {
@@ -100,6 +101,13 @@ pkg-verify () {
     if ! test -f "$pkg_root/version"; then
         error "'$pkg_spec' is not a valid package"
     fi
+}
+
+run () {
+    local cmd="$1"; shift
+
+    detect-color
+    guru-"$cmd" "$@"
 }
 
 strip-comments () {
@@ -149,26 +157,27 @@ usage () {
     echo "  --no-color  Disable color output."
 }
 
-eval set -- $(getopt -o "" --long help,list,no-color -n $exe -- "$@")
+eval set -- $(getopt -o "" --long help,list,no-color,prefix: -n $exe -- "$@")
 
 while true; do
     case "$1" in
-        --help)     usage;          exit;;
-        --list)     list-commands;  exit;;
+        --help)     usage;              exit;;
+        --list)     list-commands;      exit;;
         --no-color) disable-color;;
-        --)         shift;          break;;
-        *)                          break;;
+        --prefix)   prefix="$2";        shift 2 || error "missing prefix";;
+        --prefix=*) prefix="${1#*=}";   shift;;
+        --)                             shift; break;;
+        *)                              break;;
     esac
 done
 
-cmdname="$1"
+cmd="$1"
 
 if shift; then
-    if type -p guru-"$cmdname" &>/dev/null; then
-        detect-color
-        guru-"$cmdname" "$@"
+    if type -p guru-"$cmd" &>/dev/null; then
+        run "$cmd" "$@"
     else
-        error "'$cmdname' is not a $exe command.  Try '$exe --help'."
+        error "'$cmd' is not a $exe command.  Try '$exe --help'."
     fi
 else
     usage
